### ISSUE TITLE
Broken dependencies in Gemfiles (docker)

### ISSUE THREAD

**Issue by fabianp** [iclr-blogposts/2023#3]
The creation of the docker image fails with because of some broken ruby dependencies:
```
#10 138.9 An error occurred while installing sass-embedded (1.57.1), and Bundler cannot
#10 138.9 continue.
#10 138.9 
#10 138.9 In Gemfile:
#10 138.9   jekyll-archives was resolved to 2.2.1, which depends on
#10 138.9     jekyll was resolved to 4.3.1, which depends on
#10 138.9       jekyll-sass-converter was reso2023-01-18 07:35:36.903Z: lved to 3.0.0, which depends on
#10 138.9         sass-embedded
2023-01-18 07:35:38.375Z: #10 ERROR: executor failed running [/bin/sh -c bundle install]: exit code: 5
2023-01-18 07:35:38.445Z: ------
 > [dev_container_auto_added_stage_label 5/5] RUN bundle install:
#10 138.9 `block (2 levels) in create_threads'
#10 138.9 
#10 138.9 An error occurred while installing sass-embedded (1.57.1), and Bundler cannot
#10 138.9 continue.
#10 138.9 
#10 138.9 In Gemfile:
#10 138.9   jekyll-archives was resolved to 2.2.1, which depends on
#10 138.9     jekyll was resolved to 4.3.1, which depends on
#10 138.9       jekyll-sass-converter was resolved to 3.0.0, which depends on
#10 138.9         sass-embedded
------
```

To reproduce, just run the `./bin/docker_build_image.sh` command. 

Full stack trace here: https://gist.github.com/fabianp/d30ee45aca1fb85f282e8d83e4adc953

**Comment by busycalibrating** [comment]
Hi Fabian, I'm sorry for the trouble. I can reproduce your error - this is definitely a new issue as I tested the instructions thoroughly when we wrote them. I'll get back to you ASAP when I have an update.

For completeness, what system are you working on? (E.g. x64 Linux, x64 Windows, M1 Mac, x64 Mac, etc)

**Comment by busycalibrating** [comment]
I think the issue is resolved with the updated Dockerfile, but please let me know if you have any more trouble or reopen this if this isn't resolved for you!

**Comment by fabianp** [comment]
thanks, it seems to be working now
